### ISSUE TITLE
Check wether incoming dependencies from other metamodels/packages are considered

### ISSUE THREAD

**Issue by MishaStrittmatter** [kit-sdq-emf-refactor-fork/edu.kit.ipd.sdq.emf.refactor#2]
This concerns the smells Dead Classifier and Speculative Hierarchy. Their detection has to consider incoming dependences from other metamodels/packages. If they are not detected in the smell detection, the detection has to be modified to include them.

**Comment by aminekechaou** [comment]
Can you confirm that this only applies for incoming dependencies from the selection, not the entire workspace / plugins? If so it should be fixed by now. Please recheck.

**Comment by MishaStrittmatter** [comment]
I confirm this is fixed for all mentioned smells (dead class, dead enum, speculative hierarchy). nice job. closed
