### ISSUE TITLE
Fix the Detection of Dead Classes

### ISSUE THREAD

**Issue by MishaStrittmatter** [kit-sdq-emf-refactor-fork/edu.kit.ipd.sdq.emf.refactor#4]
See my drawing :)

**Comment by aminekechaou** [comment]
Fixed for EClass.
Do you think the implementation for EEnum ist buggy as well?

**Comment by MishaStrittmatter** [comment]
Thank you.
The Dead Enum detection should be fine. There is no inheritance between enums and nothing like containments or root containers. The only way to use them is in attributes of classes. So the implementation should be straight forward and easy to test, which I will do.
