### ISSUE TITLE
Smell detection on a project detects smells twice

### ISSUE THREAD

**Issue by MishaStrittmatter** [kit-sdq-emf-refactor-fork/edu.kit.ipd.sdq.emf.refactor#5]
Even some new smells appear. But most are simply doubled. Currently this is not a blocker, as there are more important things to fix. Simply don't start the detection on a project.

**Comment by aminekechaou** [comment]
This is probably due to the model files being present in the bin folder

**Comment by MishaStrittmatter** [comment]
Well observed, you are right. Tank you!
